baseURL = "https://github.com/angelabennedsen/minaflevering.git/"
languageCode = "en-us"
title = "By ANGELA BENNEDSEN"
theme = "gohugo-theme-ananke"
publishDir = "docs"

[params]
featured_image = "/imgs/greencup.jpg"
 background_color_class = "bg-black"
 
 [[menu.main]]
name                   = "Home"
weight                 = 1
identifier             = "home"
url                    = "/home/"

[[menu.main]]
name                   = "About"
weight                 = 2
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Contact"
weight                 = 3
identifier             = "contact"
url                    = "/contact/"

[[menu.main]]
name                   = "Portfolio"
weight                 = 4
identifier             = "portfolio"
url                    = "/portfolio/"